config/routes.rb
Rails.application.routes.draw do
  
    root'housewares#index'

  get 'housewares/index'
  
  get 'housewares/baskets_storage_racks'

  get 'housewares/cookware'

  get 'housewares/food_containers'

  get 'housewares/laundry'

  get 'housewares/tabletop_dining'

  get 'housewares/cleaning_tools'

  get 'housewares/house_chemicals'

  get 'housewares/licensed_housewares'

end

app/views/partials/_email_offer_modal.html.erb
<div class="col-md-12 col-sm-12">
<!-- <ul class="list-unstyled footer-links text-center mar-top-10">
          <li> <a href="#">Sign up  with your email to get updates!</a> </li>
        </ul> -->
              <span class="input-group-btn">
              <button type="button" class="btn btn-default border-rad-0 email-button" data-toggle="modal" data-target=".bs-example-modal-sm">

                    
               <a href="#" ><p class="font-15 font-bold mar-bot-0 mar-top-10 black">Sign up to get updates!</p></a>

                  <p class="font-20 slider-text-md deals mar-bot-0 pad-top-0"><span class="pink text-uppercase font-bold"><span class="flaticon-opened4"></span><span class="font-bold">  Email offers</span></span></p>

                  <a href="#" ><p class="font-15 mar-top-0 font-bold black"> Click here! Sign up & save.</p></a>



              </button>
              </span>

                <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                <div class="modal-dialog modal-sm">
                  <div class="modal-content">


                      <div class="panel panel-default">
                        <div class="panel-heading">
                          <h4 class="panel-title"> <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#panel1"><i class="glyphicon glyphicon-minus-sign pull-right sign"></i><img src="http://res.cloudinary.com/mckshreder/image/upload/c_fill,h_30,q_100,w_239/v1446194748/inWholsalers/Wholesalers_email_offers-logo_1.png" alt="" class="counting mar-right-0"></a> </h4>
                        </div>
                        <div id="panel1" class="panel-collapse collapse in">
                          <div class="panel-body">
                         
                            <div class="col-md-12 col-sm-12 col-xs-12">
                              <p class="font-18 font-bold mar-bot-0">email sign up</p>
                              <p class="font-12 mar-bot-0">be the first to know about new arrivals,</p>
                              <p class="font-12">exclusive offers and promotions.</p>
                              <p class="font-12 font-bold mar-bot-0 pink">sign up now for special offers via email:</p>
                              <div class="line-full mar-bot-20"></div>
                              <ul class="list-unstyled checkout-right">
                                <li>
                                  <div class="">
                                    <p>first name <span class="pink">*</span></p>
                                    <input type="text" class="form-control">
                                  </div>
                                </li>
                                <li>
                                  <div class="">
                                    <p>last name <span class="pink">*</span></p>
                                    <input type="text" class="form-control">
                                  </div>
                                </li>
                                <li>
                                  <div class="">
                                    <p>email address <span class="pink">*</span></p>
                                    <input type="text" class="form-control">
                                  </div>
                                </li>
                                <li>
                                  <div class="">
                                    <p>verify email <span class="pink">*</span></p>
                                    <input type="text" class="form-control">
                                  </div>
                                </li>
                              </ul>
                              <a class="cart pull-left" href="/" style="margin-right:16px;">sign up</a>
                              <p style="padding:8px;">See our <span class="pink">privacy policy</span></p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
         <!--  <a href="#">
             <img src="http://res.cloudinary.com/mckshreder/image/upload/c_crop,h_110,q_100,w_443/v1446188284/inWholsalers/email_offers-logo.png" class="img-responsive">
          </a> -->
        </div>

app/views/partials/_email_offer_modal_2.html.erb
<!-- 
<ul class="list-unstyled footer-links text-center mar-top-10">
          <li class="pad-0 mar-top-0">

          <p class="font-12 font-bold pink mar-0 visible-lg">Sign up  with your email to get updates!</p>
          </li>
        </ul> -->
              <span class="input-group-btn pad-top-5">
              <button type="button" class="btn btn-default mar-top-0 email-button col-sm-12 col-xs-12 border-rad-0" data-toggle="modal" data-target=".bs-example-modal-sm"> 

              
                
               <a href="#" ><p class="font-15 font-bold mar-bot-0 mar-top-10 black">Sign up to get updates!</p></a>

                  <p class="font-20 slider-text-md deals mar-bot-0 pad-top-0"><span class="pink text-uppercase font-bold"><span class="flaticon-opened4"></span><span class="font-bold">  Email offers</span></span></p>

                  <a href="#" ><p class="font-15 mar-top-0 font-bold black"> Click here! Sign up & save.</p></a>


               
         
             <!--  <img src="http://res.cloudinary.com/mckshreder/image/upload/c_crop,h_110,q_100,w_443/v1446188284/inWholsalers/email_offers-logo.png" class="img-responsive"> -->

              </button>
              </span>
<!-- fade example-modal-sm is what allows me to use it and only one -->
                <div class="modal fade example-modal-sm" tabindex="0" role="dialog" aria-labelledby="mySmallModalLabel">
                <div class="modal-dialog modal-sm">
                  <div class="modal-content">


                      <div class="panel panel-default">
                        <div class="panel-heading">
                          <h4 class="panel-title"> <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#panel2"><i class="glyphicon glyphicon-minus-sign pull-right sign"></i><img src="http://res.cloudinary.com/mckshreder/image/upload/c_fill,h_30,q_100,w_239/v1446194748/inWholsalers/Wholesalers_email_offers-logo_1.png" alt="" class="counting mar-right-0"></a> </h4>
                          
                        </div>
                        <div id="panel2" class="panel-collapse collapse in">
                          <div class="panel-body">
                         
                            <div class="col-md-12 col-sm-12 col-xs-12">
                              <p class="font-18 font-bold mar-bot-0">email sign up</p>
                              <p class="font-12 mar-bot-0">be the first to know about new arrivals,</p>
                              <p class="font-12">exclusive offers and promotions.</p>
                              <p class="font-12 font-bold mar-bot-0 pink">sign up now for special offers via email:</p>
                              <div class="line-full mar-bot-20"></div>
                              <ul class="list-unstyled checkout-right">
                                <li>
                                  <div class="">
                                    <p>first name <span class="pink">*</span></p>
                                    <input type="text" class="form-control">
                                  </div>
                                </li>
                                <li>
                                  <div class="">
                                    <p>last name <span class="pink">*</span></p>
                                    <input type="text" class="form-control">
                                  </div>
                                </li>
                                <li>
                                  <div class="">
                                    <p>email address <span class="pink">*</span></p>
                                    <input type="text" class="form-control">
                                  </div>
                                </li>
                                <li>
                                  <div class="">
                                    <p>verify email <span class="pink">*</span></p>
                                    <input type="text" class="form-control">
                                  </div>
                                </li>
                              </ul>
                              <a class="cart pull-left" href="/" style="margin-right:16px;">sign up</a>
                              <p style="padding:8px;">See our <span class="pink">privacy policy</span></p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
         <!--  <a href="#">
             <img src="http://res.cloudinary.com/mckshreder/image/upload/c_crop,h_110,q_100,w_443/v1446188284/inWholsalers/email_offers-logo.png" class="img-responsive">
          </a> -->

app/views/partials/_home_pop_up.html.erb
<div class="clearfix col-sm-12 col-xs-12 col-md-12">
<ul class="list-unstyled footer-links text-center pad-0">
          <li class="pad-0">
          <p class="font-12 font-bold pink mar-0 visible-lg">Sign up  with your email to get updates!</p>
          </li>
        </ul>
             <!--  <span class="input-group-btn">
              <button type="button" class="btn btn-default" data-toggle="modal" data-target=".bs-example-modal-sm"><img src="http://res.cloudinary.com/mckshreder/image/upload/c_crop,h_110,q_100,w_443/v1446188284/inWholsalers/email_offers-logo.png" class="img-responsive"></button>
              </span> -->
<!-- fade example-modal-sm is what allows me to use it and only one -->
                <div class="modal fade hide example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                <div class="modal-dialog modal-sm" >
                  <div class="modal-content" >


                      <div class="panel panel-default" >
                        <div class="panel-heading">
                          <h4 class="panel-title"> <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#panel3"><i class="glyphicon glyphicon-minus-sign pull-right sign"></i><img src="http://res.cloudinary.com/mckshreder/image/upload/c_fill,h_30,q_100,w_239/v1446194748/inWholsalers/Wholesalers_email_offers-logo_1.png" alt="" class="counting mar-right-0"></a> </h4>
                        </div>
                        <div id="panel " class="panel-collapse collapse in">
                          <div class="panel-body">
                         
                            <div class="col-md-12 col-sm-12 col-xs-12">
                              <p class="font-18 font-bold mar-bot-0">email sign up</p>
                              <p class="font-12 mar-bot-0">be the first to know about new arrivals,</p>
                              <p class="font-12">exclusive offers and promotions.</p>
                              <p class="font-12 font-bold mar-bot-0 pink">sign up now for special offers via email:</p>
                              <div class="line-full mar-bot-20"></div>
                              <ul class="list-unstyled checkout-right">
                                <li>
                                  <div class="">
                                    <p>first name <span class="pink">*</span></p>
                                    <input type="text" class="form-control">
                                  </div>
                                </li>
                                <li>
                                  <div class="">
                                    <p>last name <span class="pink">*</span></p>
                                    <input type="text" class="form-control">
                                  </div>
                                </li>
                                <li>
                                  <div class="">
                                    <p>email address <span class="pink">*</span></p>
                                    <input type="text" class="form-control">
                                  </div>
                                </li>
                                <li>
                                  <div class="">
                                    <p>verify email <span class="pink">*</span></p>
                                    <input type="text" class="form-control">
                                  </div>
                                </li>
                              </ul>
                              <a class="cart pull-left" href="/" style="margin-right:16px;">sign up</a>
                              <p style="padding:8px;">See our <span class="pink">privacy policy</span></p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
         <!--  <a href="#">
             <img src="http://res.cloudinary.com/mckshreder/image/upload/c_crop,h_110,q_100,w_443/v1446188284/inWholsalers/email_offers-logo.png" class="img-responsive">
          </a> -->
</div>

app/views/partials/_og_side_nav_index.html.erb
<div class="col-md-3 col-sm-4 col-md-pull-9 col-sm-pull-8 col-xs-12">

      <div class="nav-side-menu">
        <div class="category"><a href="#"><img src="../assets/images/category.jpg" alt="" class="img-responsive mar-top-0"></a></div>
        <div class="menu-list">
          <ul id="menu-content" class="menu-content collapse out">
            <!-- <li data-toggle="collapse" data-target="#home"> <a href="#"> Home <span class="arrow"></span></a>
              <ul class="sub-menu collapse" id="home">
                 <li>
                  <%= link_to('Home',housewares_index_path)%>
                </li>
              </ul>
            </li> -->

          
      <!-- for the large view -->
        <div class=" hidden-sm hidden-xs ">

        <li data-toggle="collapse" data-target="#appliances">
          <a name="Appliances" title="Appliances">Appliances<span class="arrow"></span></a>
        </li>

        <li data-toggle="collapse" data-target="#babyandkids">
          <a name="Baby, Kids &amp; Toys" title="Baby, Kids &amp; Toys">Baby, Kids & Toys<span class="arrow"></span></a>
        </li>
        
        <li data-toggle="collapse" data-target="#clothingAndHandbags">
          <a name="Clothing &amp; Handbags" title="Clothing &amp; Handbags">Clothing & Handbags<span class="arrow"></span></a>
        </li>
        
        <li data-toggle="collapse" data-target="#computersAndPrinters">
          <a name="Computers &amp; Printers" title="Computers &amp; Printers">Computers & Printers<span class="arrow"></span></a>
        </li>
        
        <li data-toggle="collapse" data-target="#electronics">
          <a name="Electronics" title="Electronics">Electronics<span class="arrow"></span></a>

        </li>
          <!-- <li data-toggle="collapse" data-target="#groceryAndFloral">
              <a name="Grocery, Floral &amp; Pets" title="Grocery, Floral &amp; Pets">Grocery, Floral & Pets<span class="arrow"></span></a>
            </li> -->
            
            <li data-toggle="collapse" data-target="#holidayGiftsAndPets">
              <a name="Holiday, Gifts &amp; Tickets" title="Holiday, Gifts &amp; Tickets">Holiday, Gifts & Tickets<span class="arrow"></span></a>
            </li>
            
           <li class="font-12" data-toggle="collapse" data-target="#homeImprovement">
              <a name="Home Improvement" title="Home Improvement">Home Improvement<span class="arrow"></span></a>
            </li>

         <li class="font-12" data-toggle="collapse" data-target="#healthAndBeauty">
              <a name="Health &amp; Beauty" title="Health &amp; Beauty">Health & Beauty<span class="arrow"></span></a>
            </li>

            <li data-toggle="collapse" data-target="#officeProducts">
            <a name="Office Products" title="Office Products">Office Products<span class="arrow"></span></a>
          </li>
            
            <li data-toggle="collapse" data-target="#homeKitchenBedAndBath">
              <a name="Home, Kitchen, Bed &amp; Bath" title="Home, Kitchen, Bed &amp; Bath">Kitchen, Bed & Bath<span class="arrow"></span></a>
            </li>

    </div>


<!-- this is the medium sized view -->
        <div class="hidden-lg hidden-md hidden-sm">

            <li class="font-12" data-toggle="collapse" data-target="#appliances">
              <a name="Appliances" title="Appliances">Appliances<span class="arrow"></span></a>
            </li>

            <li class="font-12" data-toggle="collapse" data-target="#babyandkids">
              <a name="Baby, Kids &amp; Toys" title="Baby, Kids &amp; Toys">Baby, Kids & Toys<span class="arrow"></span></a>
            </li>
            
            <li class="font-12" data-toggle="collapse" data-target="#clothingAndHandbags">
              <a name="Clothing &amp; Handbags" title="Clothing &amp; Handbags">Clothing & Handbags<span class="arrow"></span></a>
            </li>
            
            <li class="font-12" data-toggle="collapse" data-target="#computersAndPrinters">
              <a name="Computers &amp; Printers" title="Computers &amp; Printers">Computers & Printers<span class="arrow"></span></a>
            </li>
            
            <li class="font-12" data-toggle="collapse" data-target="#electronics">
              <a name="Electronics" title="Electronics">Electronics<span class="arrow"></span></a>
            </li>

            <li data-toggle="collapse" data-target="#holidayGiftsAndPets">
                  <a name="Holiday, Gifts &amp; Tickets" title="Holiday, Gifts &amp; Tickets">Holiday, Gifts & Tickets<span class="arrow"></span></a>
                </li>
                
               <li class="font-12" data-toggle="collapse" data-target="#homeImprovement">
                  <a name="Home Improvement" title="Home Improvement">Home Improvement<span class="arrow"></span></a>
                </li>

            
           
            
          <li class="font-12" data-toggle="collapse" data-target="#healthAndBeauty">
              <a name="Health &amp; Beauty" title="Health &amp; Beauty">Health & Beauty<span class="arrow"></span></a>
            </li>

            <li data-toggle="collapse" data-target="#officeProducts">
            <a name="Office Products" title="Office Products">Office Products<span class="arrow"></span></a>
          </li>
            
            <li data-toggle="collapse" data-target="#homeKitchenBedAndBath">
              <a name="Home, Kitchen, Bed &amp; Bath" title="Home, Kitchen, Bed &amp; Bath">Kitchen, Bed & Bath<span class="arrow"></span></a>
            </li>
            
          
            
           

        </div>
        
        <!-- for the small view -->
        <div class=" hidden-md hidden-lg hidden-xs">
             <li data-toggle="collapse" data-target="#appliances">
              <a name="Appliances" title="Appliances">Appliances<span class="arrow"></span></a>
            </li>

            <li data-toggle="collapse" data-target="#babyandkids">
              <a name="Baby, Kids &amp; Toys" title="Baby, Kids &amp; Toys">Baby, Kids & Toys<span class="arrow"></span></a>
            </li>
            
            <li data-toggle="collapse" data-target="#clothingAndHandbags">
              <a name="Clothing &amp; Handbags" title="Clothing &amp; Handbags">Clothing & Handbags<span class="arrow"></span></a>
            </li>
            
            <li data-toggle="collapse" data-target="#computersAndPrinters">
              <a name="Computers &amp; Printers" title="Computers &amp; Printers">Computers & Printers<span class="arrow"></span></a>
            </li>
            
            <li data-toggle="collapse" data-target="#electronics">
              <a name="Electronics" title="Electronics">Electronics<span class="arrow"></span></a>

            </li>

             <li data-toggle="collapse" data-target="#holidayGiftsAndPets">
                  <a name="Holiday, Gifts &amp; Tickets" title="Holiday, Gifts &amp; Tickets">Holiday, Gifts & Tickets<span class="arrow"></span></a>
                </li>
                
               <li class="font-12" data-toggle="collapse" data-target="#homeImprovement">
                  <a name="Home Improvement" title="Home Improvement">Home Improvement<span class="arrow"></span></a>
                </li>

         
         
        </div>



        
        
       <!--  <li data-toggle="collapse" data-target="#patioAndOutdoor">
          <a name="Patio &amp; Outdoor" title="Patio &amp; Outdoor">Patio & Outdoor<span class="arrow"></span></a>
        </li> -->
        <!--
        <li data-toggle="collapse" data-target="#sportsAndFitness">
          <a name="Sports &amp; Fitness" title="Sports &amp; Fitness">Sports & Fitness<span class="arrow"></span></a>
        </li>
        
        <li data-toggle="collapse" data-target="#travelAndLuggage">
          <a name="Travel &amp; Luggage" title="Travel &amp; Luggage">Travel & Luggage<span class="arrow"></span></a>
        </li>  -->
        
        <li data-toggle="collapse" data-target="#viewMoreCategories">
          <a name="View More Categories" title="View More Categories">View All Categories<span class="arrow"></span></a>
        </li>
        <%= render "partials/mobile_nav_dropdown"%>
       
        <li class="hvr-float">
         <%= render "partials/email_offer_modal_2"%>
        </li>
      


           <!--  <li data-toggle="collapse" data-target="#cleaning"> <a href="#"> Cleaning Tools<span class="arrow"></span></a>
              <ul class="sub-menu collapse" id="cleaning">
                 <li>
                  <%= link_to('Cleaning Tools',housewares_cleaning_tools_path)%>
                </li>
              </ul>
            </li>
            <li data-toggle="collapse" data-target="#chemicals"> <a href="#"> Household Chemicals<span class="arrow"></span></a>
              <ul class="sub-menu collapse" id="chemicals">
                 <li>
                <%= link_to('Household Chemicals',housewares_house_chemicals_path)%>
                </li>
              </ul>
            </li>
            <li data-toggle="collapse" data-target="#cookware"> <a href="#"> Cookware <span class="arrow"></span></a>
              <ul class="sub-menu collapse" id="cookware">
                  <li>
                  <%= link_to('Cookware',housewares_cookware_path)%>
                </li>
              </ul>
            </li>
            <li data-toggle="collapse" data-target="#food"> <a href="#"> Food Containers<span class="arrow"></span></a>
              <ul class="sub-menu collapse" id="food">
                 <li>
                  <%= link_to('Food Containers',housewares_food_containers_path)%>
                </li>
              </ul>
            </li>
            <li data-toggle="collapse" data-target="#laundry"> <a href="#"> Laundry <span class="arrow"></span></a>
              <ul class="sub-menu collapse" id="laundry">
                 <li>
                  <%= link_to('Laundry',housewares_laundry_path)%>
                </li>
              </ul>
            </li>
            <li data-toggle="collapse" data-target="#table_top"> <a href="#"> Tabletop Dining<span class="arrow"></span></a>
              <ul class="sub-menu collapse" id="table_top">
                 <li>
                  <%= link_to('Tabletop Dining', housewares_tabletop_dining_path)%>
                </li>
              </ul>
            </li>
            <li data-toggle="collapse" data-target="#lics"> <a href="#"> Licensed Housewares<span class="arrow"></span></a>
              <ul class="sub-menu collapse" id="lics">
                 <li>
                  <%= link_to('Licensed Housewares',housewares_licensed_housewares_path)%>
                  </li>
              </ul>
            </li> -->

               
       
            
          </ul>
        </div>
      </div>
       <!-- <ul class="list-unstyled images-3 hidden-sm hidden-xs">
        <li><img src="../assets/images/free.jpg" alt="" class="img-responsive"></li>
        <li><img src="../assets/images/off.jpg" alt="" class="img-responsive"></li>
      </ul> -->
    </div>
<script src="../assets/js/jquery-v11.js"></script> 

<!-- Include all compiled plugins (below), or include individual files as needed --> 
<script src="../assets/js/bootstrap.min.js"></script> 

<!-- Main Scripts--> 

<script src="../assets/js/search.js"></script> 
<script src="../assets/js/ttmenu.js"></script> 

<script src="../assets/js/custom.js"></script> 
<script>

cdtd();</script><!--animations--> 
<script src="../assets/js/wow.min.js"></script> 
<script>
 new WOW().init();
 new WOW.sync();
</script>

app/views/partials/_unused_index.html.erb
<div class="row tabs-sec main-body-mar hidden-xs">
          <div class="col-sm-12 col-xs-12">
            <div class="feature clearfix">

      <!-- <ul class="list-unstyled list-inline hidden-sm hidden-xs mar-0">
        <li class="mar-left-30 pad-right-0"><img src="https://res.cloudinary.com/mckshreder/image/upload/c_limit,h_45,o_75,q_100,w_275/v1445588545/Free_Shipping_-logo_11_cjrew5.png" alt="" class="img-responsive"></li>
        <li class="mar-left-30 pad-right-0"><img src="https://res.cloudinary.com/mckshreder/image/upload/c_limit,h_45,o_75,q_100,w_275/v1445588299/No_Minimum_Order-logo_q36bfo.png" alt="" class="img-responsive"></li>
        <li class="mar-left-30 pad-right-0"><img src="https://res.cloudinary.com/mckshreder/image/upload/c_limit,h_45,o_75,q_100,w_275/v1445588138/Order_Bulk_Save-logo_2_y9mdhx.png" alt="" class="img-responsive"></li>
      </ul> -->
            <!-- <div class="feature"> -->
              <p class="font-16 slider-text-md col-sm-12 text-uppercase deals"><span class="font-bold">Stock up on all your favorite products</span>&nbsp;&nbsp;<span class="pull-right">D<span class="text-lowercase">elivered to your door for<span class="font-bold text-uppercase"> free!</span></span></span></p>

              <!-- <p class="font-13 text-uppercase text-center deals hidden-lg hidden-md hidden-sm col-xs-12"><span class="font-bold">All your favorite products!</span><br><span class="">D<span class="text-lowercase">elivered to your door for<span class="font-bold text-uppercase"> free!</span></span></span></p> -->


            
             <!--  <p class="font-18 text-uppercase deals"><span class="font-bold">amazing discounts and great margins</span>&nbsp;<span class="text-lowercase">on your most trusted brands and licenses.</p> -->
            <!-- </div> -->
              <p class="font-16 text-uppercase text-center deals hidden-lg hidden-md hidden-sm hidden-xs">

                <span class="font-bold">All of your favorite products</span><br><span class="">D<span class="text-lowercase">elivered to your door for<span class="font-bold text-uppercase pink"> free!</span></span></span>
                
              </p>

            </div>
          </div>
        </div>


            <!-- <img src="https://res.cloudinary.com/mckshreder/image/upload/c_crop,h_50,q_100,w_880/v1445749925/inWholsalers/in-wholesaler-slider-header1.png" class="img-responsive mar-top-0"> -->


<!-- the start of the cell carousel -->
      <div data-example-id="simple-carousel" class="below-headeer hidden-lg hidden-md col-sm-12 col-xs-12 pad-0">


      


           
         




         <!-- <div class="font-13 text-uppercase text-center">
            
            <ul class="list-unstyled list-inline mar-0 pull-left col-xs-12">
              <li class="pad-left-0 pad-right-0 col-xs-4"><img src="https://res.cloudinary.com/mckshreder/image/upload/c_limit,h_40,o_75,q_100,w_300/v1445588299/No_Minimum_Order-logo_q36bfo.png" alt="" class="img-responsive pad-top-0"></li>
              <li class="pad-left-0 pad-right-0 col-xs-4"><img src="https://res.cloudinary.com/mckshreder/image/upload/c_limit,h_40,o_75,q_100,w_300/v1445588138/Order_Bulk_Save-logo_2_y9mdhx.png" alt="" class="img-responsive pad-top-0"></li>
              <li class="mar-left-0 pad-right-0 col-xs-4"><img src="https://res.cloudinary.com/mckshreder/image/upload/c_limit,h_40,o_75,q_100,w_300/v1445588545/Free_Shipping_-logo_11_cjrew5.png" alt="" class="img-responsive pad-top-0"></li>
            </ul>

          </div> -->
       
      </div>



 
       <!--  <div class="row tabs-sec">
          <div class="col-xs-12 clearfix">
            <div class="feature clearfix wow bounceInLeft" data-wow-duration="2s">
              
              <p class="font-18 text-uppercase deals"><span class="font-bold">inWholesalers</span>&nbsp;<span class="pull-right">O<span class="text-lowercase">nline shopping made easy</span></span></p>

      <ul class="list-unstyled list-inline hidden-sm hidden-xs mar-0 mar-top-20">
        <li class="pad-left-0 pad-right-0"><img src="https://res.cloudinary.com/mckshreder/image/upload/c_limit,h_63,o_75,q_100,w_284/v1445588545/Free_Shipping_-logo_11_cjrew5.png" alt="" class="img-responsive"></li>
        <li class="pad-left-0 pad-right-0"><img src="https://res.cloudinary.com/mckshreder/image/upload/c_limit,h_63,o_75,q_100,w_284/v1445588299/No_Minimum_Order-logo_q36bfo.png" alt="" class="img-responsive"></li>
        <li class="pad-left-0 pad-right-0"><img src="https://res.cloudinary.com/mckshreder/image/upload/c_limit,h_63,o_75,q_100,w_284/v1445588138/Order_Bulk_Save-logo_2_y9mdhx.png" alt="" class="img-responsive"></li>
      </ul>
            </div>
          </div>
        </div>

 -->

     

<!-- <br> -->